{
 "title": "My Dashboard",
 "description": "Simple info",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "General info",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "python_info" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_virtual_memory_bytes{}" },
    {
     "expr": "process_resident_memory_bytes{}"
    }
   ]
  },
  {
   "title": "Gb collected objects",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "python_gc_objects_collected_total{}",
     "legendFormat": "Total collected by gb"
    },
    {
     "expr": "python_gc_objects_uncollectable_total{}",
     "legendFormat": "Uncollectable total"
    },
    { "expr": "python_gc_collections_total{}" }
   ]
  }
 ]
}